//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastosResidenciais.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GastosResidenciais.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo idade é obrigatório.
        /// </summary>
        public static string AGE_EMPTY {
            get {
                return ResourceManager.GetString("AGE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade tem que ser menor do que 100.
        /// </summary>
        public static string AGE_LESSER_THAN {
            get {
                return ResourceManager.GetString("AGE_LESSER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo descrição é obrigatório.
        /// </summary>
        public static string DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve conter no máximo 22 caracteres.
        /// </summary>
        public static string DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não são permitidos caracteres especiais.
        /// </summary>
        public static string DESCRIPTION_SPECIAL_CARACTERS {
            get {
                return ResourceManager.GetString("DESCRIPTION_SPECIAL_CARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo ID é obrigatório.
        /// </summary>
        public static string ID_EMPTY {
            get {
                return ResourceManager.GetString("ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários menores de 18 anos não podem cadastrar receitas.
        /// </summary>
        public static string INVALID_TRANSACTION_FOR_UNDERAGE {
            get {
                return ResourceManager.GetString("INVALID_TRANSACTION_FOR_UNDERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome deve conter no máximo 25 caracteres.
        /// </summary>
        public static string NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome não pode conter caracteres especiais.
        /// </summary>
        public static string NAME_SPECIAL_CARACTERS {
            get {
                return ResourceManager.GetString("NAME_SPECIAL_CARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo inserido não é válido.
        /// </summary>
        public static string TYPE_INVALID {
            get {
                return ResourceManager.GetString("TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo tipo é obrigatório.
        /// </summary>
        public static string TYPES_EMPTY {
            get {
                return ResourceManager.GetString("TYPES_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo user id é obrigatório.
        /// </summary>
        public static string USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("USER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo valor é obrigatório.
        /// </summary>
        public static string VALOR_EMPTY {
            get {
                return ResourceManager.GetString("VALOR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor inserido deve ser maior que 0.
        /// </summary>
        public static string VALOR_GREATER_THAN_0 {
            get {
                return ResourceManager.GetString("VALOR_GREATER_THAN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor não permitido.
        /// </summary>
        public static string VALOR_LESSER_THAN {
            get {
                return ResourceManager.GetString("VALOR_LESSER_THAN", resourceCulture);
            }
        }
    }
}
